### ISSUE TITLE
export net.http.Client

### ISSUE THREAD

**Issue by mattn** [mattn/go-redmine#1]
Possible to access via basic auth.

**Comment by robvdl** [comment]
I am not quite sure what you mean sorry.

I wanted to create a simple function in my own code that takes a *redmine.Client as argument so that I can call methods on it, but I cannot see how that is possible if redmine.Client is not exported.

// can't do this because redmine.client needs to be exported
func myFunc(c *redmine.client) {
    c.IssuesOf(155)
    c.IssuesByFilter(....)
}

func main() {
    c := redmine.NewClient(...)
    myFunc(c)
}
